import MemberLayout from '@/Components/Layouts/MemberLayout';
import { Head, Link } from '@inertiajs/react';
import { Eye, FolderKanban, RotateCcw } from 'lucide-react';
import { formatDate } from '@/lib/utils';

interface Project { id: number; title: string; notes: string | null; preview_url: string; order_id: number | null; order_no: string | null; created_at: string }

export default function MemberProjectsIndex({ projects }: { projects: Project[] }) {
  return <MemberLayout><Head title="Design Saya" /><div className="mx-auto max-w-[1280px] px-4 py-8 lg:px-8"><div className="mb-8"><h1 className="text-2xl font-bold text-slate-900">Design Saya</h1><p className="mt-1 text-sm text-slate-500">Preview design tempahan anda. File source hanya disimpan untuk kegunaan admin.</p></div>{projects.length === 0 ? <div className="frontend-flat-card py-16 text-center"><FolderKanban className="mx-auto h-12 w-12 text-slate-300" /><p className="mt-3 font-semibold text-slate-900">Belum ada design</p><p className="mt-1 text-sm text-slate-500">Design yang telah dimasukkan oleh admin akan muncul di sini.</p></div> : <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{projects.map((project) => <article key={project.id} className="frontend-flat-card overflow-hidden"><div className="flex h-[250px] items-center justify-center bg-slate-100"><img src={project.preview_url} alt={`${project.title} preview`} className="max-h-[250px] max-w-full object-contain" /></div><div className="space-y-3 p-5"><div><h2 className="font-bold text-slate-900">{project.title}</h2><p className="mt-1 text-xs text-slate-500">{project.order_no ? `Order ${project.order_no}` : 'Project customer'} · {formatDate(project.created_at)}</p></div>{project.notes && <p className="text-sm text-slate-600">{project.notes}</p>}<div className="flex flex-wrap gap-2">{project.order_id && <Link href={route('member.orders.repeat', project.order_id)} method="post" as="button" type="button" className="frontend-btn-primary text-xs"><RotateCcw className="h-3.5 w-3.5" />Order Design Ini Lagi</Link>}<a href={project.preview_url} target="_blank" rel="noreferrer" className="frontend-btn-secondary text-xs"><Eye className="h-3.5 w-3.5" />Lihat Preview</a></div></div></article>)}</div>}</div></MemberLayout>;
}
